In [10]:
import py7zr
import re
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json
PROCESSED_DIR = Path('data/processed')
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

In [11]:
ZIP_DIR = Path('zips')
RAW_DIR = Path('data/raw')

def unzip_all(zip_dir, raw_dir):
    for zip_path in sorted(zip_dir.glob('*.7z')):
        year = re.search(r'20\d{2}', zip_path.name).group()
        out_dir = raw_dir / year
        out_dir.mkdir(parents=True, exist_ok=True)
        with py7zr.SevenZipFile(zip_path, 'r') as z:
            z.extractall(out_dir)
        print(f'{zip_path.name}  ->  {out_dir}')

unzip_all(ZIP_DIR, RAW_DIR)

spx_eod_2010-hixkhi.7z  ->  data\raw\2010
spx_eod_2011-mpv77a.7z  ->  data\raw\2011
spx_eod_2012-ftrobg.7z  ->  data\raw\2012
spx_eod_2013-3p7m9u.7z  ->  data\raw\2013
spx_eod_2014-4ky8n2.7z  ->  data\raw\2014
spx_eod_2015-amtjlk.7z  ->  data\raw\2015
spx_eod_2016-rctzlw.7z  ->  data\raw\2016
spx_eod_2017-xspity.7z  ->  data\raw\2017
spx_eod_2018-uqawfl.7z  ->  data\raw\2018
spx_eod_2019-chxexe.7z  ->  data\raw\2019
spx_eod_2020-wh6jt7.7z  ->  data\raw\2020
spx_eod_2021-n4uqkm.7z  ->  data\raw\2021
spx_eod_2021q3-kgzold.7z  ->  data\raw\2021
spx_eod_2021q4-r3h0dx.7z  ->  data\raw\2021
spx_eod_2022q1-ff0r18.7z  ->  data\raw\2022
spx_eod_2022q2-bxgzw0.7z  ->  data\raw\2022
spx_eod_2022q3-1f2afi.7z  ->  data\raw\2022
spx_eod_2022q4-dmme3k.7z  ->  data\raw\2022
spx_eod_2023q1-cfph7w.7z  ->  data\raw\2023
spx_eod_2023q2-kdxt36.7z  ->  data\raw\2023
spx_eod_2023q3-w9b0jk.7z  ->  data\raw\2023
spx_eod_2023q4-ai4uc9.7z  ->  data\raw\2023

In [12]:
txt_files = sorted(RAW_DIR.rglob('*.txt'))
print('Number of .txt files:', len(txt_files))
for f in txt_files:
    print(f, '|', round(f.stat().st_size / 1e6, 1), 'MB')

Number of .txt files: 168
data\raw\2010\spx_eod_201001.txt | 6.1 MB
data\raw\2010\spx_eod_201002.txt | 5.9 MB
data\raw\2010\spx_eod_201003.txt | 7.4 MB
data\raw\2010\spx_eod_201004.txt | 6.8 MB
data\raw\2010\spx_eod_201005.txt | 6.4 MB
data\raw\2010\spx_eod_201006.txt | 7.5 MB
data\raw\2010\spx_eod_201007.txt | 6.8 MB
data\raw\2010\spx_eod_201008.txt | 7.5 MB
data\raw\2010\spx_eod_201009.txt | 7.4 MB
data\raw\2010\spx_eod_201010.txt | 6.9 MB
data\raw\2010\spx_eod_201011.txt | 6.6 MB
data\raw\2010\spx_eod_201012.txt | 7.5 MB
data\raw\2011\spx_eod_201101.txt | 5.3 MB
data\raw\2011\spx_eod_201102.txt | 6.7 MB
data\raw\2011\spx_eod_201103.txt | 8.2 MB
data\raw\2011\spx_eod_201104.txt | 6.9 MB
data\raw\2011\spx_eod_201105.txt | 7.5 MB
data\raw\2011\spx_eod_201106.txt | 7.7 MB
data\raw\2011\spx_eod_201107.txt | 6.9 MB
data\raw\2011\spx_eod_201108.txt | 8.1 MB
data\raw\2011\spx_eod_201109.txt | 8.1 MB
data\raw\2011\spx_eod_201110.txt | 7.7 MB
data\raw\2011\spx_eod_201111.txt | 7.6 MB
data\raw\2011\spx_eod_201112.txt | 7.6 MB
data\raw\2012\spx_eod_201201.txt | 7.4 MB
data\raw\2012\spx_eod_201202.txt | 7.8 MB
data\raw\2012\spx_eod_201203.txt | 9.3 MB
data\raw\2012\spx_eod_201204.txt | 8.2 MB
data\raw\2012\spx_eod_201205.txt | 8.9 MB
data\raw\2012\spx_eod_201206.txt | 9.4 MB
data\raw\2012\spx_eod_201207.txt | 9.9 MB
data\raw\2012\spx_eod_201208.txt | 11.5 MB
data\raw\2012\spx_eod_201209.txt | 9.3 MB
data\raw\2012\spx_eod_201210.txt | 11.3 MB
data\raw\2012\spx_eod_201211.txt | 11.3 MB
data\raw\2012\spx_eod_201212.txt | 10.3 MB
data\raw\2013\spx_eod_201301.txt | 10.4 MB
data\raw\2013\spx_eod_201302.txt | 9.6 MB
data\raw\2013\spx_eod_201303.txt | 10.0 MB
data\raw\2013\spx_eod_201304.txt | 11.6 MB
data\raw\2013\spx_eod_201305.txt | 12.3 MB
data\raw\2013\spx_eod_201306.txt | 11.0 MB
data\raw\2013\spx_eod_201307.txt | 13.0 MB
data\raw\2013\spx_eod_201308.txt | 13.3 MB
data\raw\2013\spx_eod_201309.txt | 12.3 MB
data\raw\2013\spx_eod_201310.txt | 13.8 MB
data\raw\2013\spx_eod_201311.txt | 12.7 MB
data\raw\2013\spx_eod_201312.txt | 13.6 MB
data\raw\2014\spx_eod_201401.txt | 14.0 MB
data\raw\2014\spx_eod_201402.txt | 14.3 MB
data\raw\2014\spx_eod_201403.txt | 16.5 MB
data\raw\2014\spx_eod_201404.txt | 15.8 MB
data\raw\2014\spx_eod_201405.txt | 16.0 MB
data\raw\2014\spx_eod_201406.txt | 16.1 MB
data\raw\2014\spx_eod_201407.txt | 18.0 MB
data\raw\2014\spx_eod_201408.txt | 17.9 MB
data\raw\2014\spx_eod_201409.txt | 21.1 MB
data\raw\2014\spx_eod_201410.txt | 24.0 MB
data\raw\2014\spx_eod_201411.txt | 21.0 MB
data\raw\2014\spx_eod_201412.txt | 23.6 MB
data\raw\2015\spx_eod_201501.txt | 22.3 MB
data\raw\2015\spx_eod_201502.txt | 22.5 MB
data\raw\2015\spx_eod_201503.txt | 29.2 MB
data\raw\2015\spx_eod_201504.txt | 27.8 MB
data\raw\2015\spx_eod_201505.txt | 26.5 MB
data\raw\2015\spx_eod_201506.txt | 30.5 MB
data\raw\2015\spx_eod_201507.txt | 30.6 MB
data\raw\2015\spx_eod_201508.txt | 31.4 MB
data\raw\2015\spx_eod_201509.txt | 34.0 MB
data\raw\2015\spx_eod_201510.txt | 30.9 MB
data\raw\2015\spx_eod_201511.txt | 27.4 MB
data\raw\2015\spx_eod_201512.txt | 29.4 MB
data\raw\2016\spx_eod_201601.txt | 24.5 MB
data\raw\2016\spx_eod_201602.txt | 26.1 MB
data\raw\2016\spx_eod_201603.txt | 29.9 MB
data\raw\2016\spx_eod_201604.txt | 26.5 MB
data\raw\2016\spx_eod_201605.txt | 26.0 MB
data\raw\2016\spx_eod_201606.txt | 25.4 MB
data\raw\2016\spx_eod_201607.txt | 24.8 MB
data\raw\2016\spx_eod_201608.txt | 28.5 MB
data\raw\2016\spx_eod_201609.txt | 27.8 MB
data\raw\2016\spx_eod_201610.txt | 29.6 MB
data\raw\2016\spx_eod_201611.txt | 28.2 MB
data\raw\2016\spx_eod_201612.txt | 31.1 MB
data\raw\2017\spx_eod_201701.txt | 29.8 MB
data\raw\2017\spx_eod_201702.txt | 27.3 MB
data\raw\2017\spx_eod_201703.txt | 32.8 MB
data\raw\2017\spx_eod_201704.txt | 27.0 MB
data\raw\2017\spx_eod_201705.txt | 30.8 MB
data\raw\2017\spx_eod_201706.txt | 30.7 MB
data\raw\2017\spx_eod_201707.txt | 27.3 MB
data\raw\2017\spx_eod_201708.txt | 31.4 MB
data\raw\2017\spx_eod_201709.txt | 27.1 MB
data\raw\2017\spx_eod_201710.txt | 32.0 MB
data\raw\2017\spx_eod_201711.txt | 31.4 MB
data\raw\2017\spx_eod_201712.txt | 30.7 MB
data\raw\2018\spx_eod_201801.txt | 34.4 MB
data\raw\2018\spx_eod_201802.txt | 34.8 MB
data\raw\2018\spx_eod_201803.txt | 38.9 MB
data\raw\2018\spx_eod_201804.txt | 40.0 MB
data\raw\2018\spx_eod_201805.txt | 41.0 MB
data\raw\2018\spx_eod_201806.txt | 39.2 MB
data\raw\2018\spx_eod_201807.txt | 41.4 MB
data\raw\2018\spx_eod_201808.txt | 45.9 MB
data\raw\2018\spx_eod_201809.txt | 38.3 MB
data\raw\2018\spx_eod_201810.txt | 48.8 MB
data\raw\2018\spx_eod_201811.txt | 45.4 MB
data\raw\2018\spx_eod_201812.txt | 42.6 MB
data\raw\2019\spx_eod_201901.txt | 45.8 MB
data\raw\2019\spx_eod_201902.txt | 39.0 MB
data\raw\2019\spx_eod_201903.txt | 39.6 MB
data\raw\2019\spx_eod_201904.txt | 42.2 MB
data\raw\2019\spx_eod_201905.txt | 41.3 MB
data\raw\2019\spx_eod_201906.txt | 39.6 MB
data\raw\2019\spx_eod_201907.txt | 45.3 MB
data\raw\2019\spx_eod_201908.txt | 44.8 MB
data\raw\2019\spx_eod_201909.txt | 37.8 MB
data\raw\2019\spx_eod_201910.txt | 46.8 MB
data\raw\2019\spx_eod_201911.txt | 44.8 MB
data\raw\2019\spx_eod_201912.txt | 49.0 MB
data\raw\2020\spx_eod_202001.txt | 50.4 MB
data\raw\2020\spx_eod_202002.txt | 47.5 MB
data\raw\2020\spx_eod_202003.txt | 65.7 MB
data\raw\2020\spx_eod_202004.txt | 54.0 MB
data\raw\2020\spx_eod_202005.txt | 44.4 MB
data\raw\2020\spx_eod_202006.txt | 50.7 MB
data\raw\2020\spx_eod_202007.txt | 51.9 MB
data\raw\2020\spx_eod_202008.txt | 49.8 MB
data\raw\2020\spx_eod_202009.txt | 55.7 MB
data\raw\2020\spx_eod_202010.txt | 54.2 MB
data\raw\2020\spx_eod_202011.txt | 46.7 MB
data\raw\2020\spx_eod_202012.txt | 53.7 MB
data\raw\2021\spx_eod_202101.txt | 51.4 MB
data\raw\2021\spx_eod_202102.txt | 49.6 MB
data\raw\2021\spx_eod_202103.txt | 64.3 MB
data\raw\2021\spx_eod_202104.txt | 62.9 MB
data\raw\2021\spx_eod_202105.txt | 57.4 MB
data\raw\2021\spx_eod_202106.txt | 62.2 MB
data\raw\2021\spx_eod_202107.txt | 64.2 MB
data\raw\2021\spx_eod_202108.txt | 64.6 MB
data\raw\2021\spx_eod_202109.txt | 58.3 MB
data\raw\2021\spx_eod_202110.txt | 68.9 MB
data\raw\2021\spx_eod_202111.txt | 71.9 MB
data\raw\2021\spx_eod_202112.txt | 75.6 MB
data\raw\2022\spx_eod_202201.txt | 67.9 MB
data\raw\2022\spx_eod_202202.txt | 59.4 MB
data\raw\2022\spx_eod_202203.txt | 67.1 MB
data\raw\2022\spx_eod_202204.txt | 58.6 MB
data\raw\2022\spx_eod_202205.txt | 62.5 MB
data\raw\2022\spx_eod_202206.txt | 60.3 MB
data\raw\2022\spx_eod_202207.txt | 59.4 MB
data\raw\2022\spx_eod_202208.txt | 65.0 MB
data\raw\2022\spx_eod_202209.txt | 65.2 MB
data\raw\2022\spx_eod_202210.txt | 63.8 MB
data\raw\2022\spx_eod_202211.txt | 64.2 MB
data\raw\2022\spx_eod_202212.txt | 60.8 MB
data\raw\2023\spx_eod_202301.txt | 51.9 MB
data\raw\2023\spx_eod_202302.txt | 53.2 MB
data\raw\2023\spx_eod_202303.txt | 64.1 MB
data\raw\2023\spx_eod_202304.txt | 52.0 MB
data\raw\2023\spx_eod_202305.txt | 58.5 MB
data\raw\2023\spx_eod_202306.txt | 59.8 MB
data\raw\2023\spx_eod_202307.txt | 58.9 MB
data\raw\2023\spx_eod_202308.txt | 67.7 MB
data\raw\2023\spx_eod_202309.txt | 60.7 MB
data\raw\2023\spx_eod_202310.txt | 67.3 MB
data\raw\2023\spx_eod_202311.txt | 65.5 MB
data\raw\2023\spx_eod_202312.txt | 64.0 MB

In [13]:
with open(txt_files[0]) as f:
    print(f.readline())
    print(f.readline())

[QUOTE_UNIXTIME], [QUOTE_READTIME], [QUOTE_DATE], [QUOTE_TIME_HOURS], [UNDERLYING_LAST], [EXPIRE_DATE], [EXPIRE_UNIX], [DTE], [C_DELTA], [C_GAMMA], [C_VEGA], [C_THETA], [C_RHO], [C_IV], [C_VOLUME], [C_LAST], [C_SIZE], [C_BID], [C_ASK], [STRIKE], [P_BID], [P_ASK], [P_SIZE], [P_LAST], [P_DELTA], [P_GAMMA], [P_VEGA], [P_THETA], [P_RHO], [P_IV], [P_VOLUME], [STRIKE_DISTANCE], [STRIKE_DISTANCE_PCT]

1262638800, 2010-01-04 16:00, 2010-01-04, 16.000000, 1132.990000, 2010-01-07, 1262898000, 3.000000, 1.000000, 0.000000, 0.000000, 0.000000, 0.000000, , , 0.000000, 101 x 101, 205.990000, 208.990000, 925.000000, 0.000000, 0.060000, 0 x 420, 0.050000, -0.000770, 0.000040, 0.004390, -0.021160, -0.000490, 0.640130, 550.000000, 208.000000, 0.184000

In [14]:
def read_header(path):
    with open(path) as f:
        return [c.strip().strip('[]').lower() for c in f.readline().strip().split(',')]

ref = read_header(txt_files[0])
print(len(ref), 'columns:', ref)

for f in txt_files:
    if read_header(f) != ref:
        print('DIFFERENT:', f.name)
print('Check done')

33 columns: ['quote_unixtime', 'quote_readtime', 'quote_date', 'quote_time_hours', 'underlying_last', 'expire_date', 'expire_unix', 'dte', 'c_delta', 'c_gamma', 'c_vega', 'c_theta', 'c_rho', 'c_iv', 'c_volume', 'c_last', 'c_size', 'c_bid', 'c_ask', 'strike', 'p_bid', 'p_ask', 'p_size', 'p_last', 'p_delta', 'p_gamma', 'p_vega', 'p_theta', 'p_rho', 'p_iv', 'p_volume', 'strike_distance', 'strike_distance_pct']
Check done

In [15]:
KEEP = ['quote_date', 'underlying_last', 'expire_date', 'dte', 'strike',
        'c_bid', 'c_ask', 'c_last', 'c_volume', 'c_size',
        'c_iv', 'c_delta', 'c_gamma', 'c_vega', 'c_theta', 'c_rho']

def load_calls(path):
    return pd.read_csv(path,
                       names=ref, header=0, 
                       usecols=KEEP,
                       skipinitialspace=True,     
                       low_memory=False)

calls = pd.concat([load_calls(f) for f in txt_files], ignore_index=True)
calls['quote_date'] = pd.to_datetime(calls['quote_date'])
calls['expire_date'] = pd.to_datetime(calls['expire_date'])

print(calls.shape)
print(calls.dtypes)
calls.head()

(15556477, 16)
quote_date         datetime64[us]
underlying_last           float64
expire_date        datetime64[us]
dte                       float64
c_delta                   float64
c_gamma                   float64
c_vega                    float64
c_theta                   float64
c_rho                     float64
c_iv                      float64
c_volume                  float64
c_last                    float64
c_size                        str
c_bid                     float64
c_ask                     float64
strike                    float64
dtype: object

,quote_date,underlying_last,expire_date,dte,c_delta,c_gamma,c_vega,c_theta,c_rho,c_iv,c_volume,c_last,c_size,c_bid,c_ask,strike
0,2010-01-04,1132.99,2010-01-07,3.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,101 x 101,205.99,208.99,925.0
1,2010-01-04,1132.99,2010-01-07,3.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,101 x 101,181.00,184.00,950.0
2,2010-01-04,1132.99,2010-01-07,3.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,101 x 101,156.00,159.00,975.0
3,2010-01-04,1132.99,2010-01-07,3.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,101 x 101,131.10,134.10,1000.0
4,2010-01-04,1132.99,2010-01-07,3.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,101 x 101,106.21,109.20,1025.0

In [16]:

calls['mid'] = (calls['c_bid'] + calls['c_ask']) / 2

calls['moneyness'] = calls['underlying_last'] / calls['strike']

print('First date:', calls['quote_date'].min().date())
print('Last date: ', calls['quote_date'].max().date())
print('Trading days:', calls['quote_date'].nunique())

calls[['mid', 'underlying_last', 'strike', 'moneyness', 'dte']].describe()

calls['year'] = calls['quote_date'].dt.year

First date: 2010-01-04
Last date:  2023-12-29
Trading days: 3499

In [17]:
problems = pd.Series({
    'missing bid or ask':     calls[['c_bid', 'c_ask']].isna().any(axis=1).sum(),
    'bid = 0':                (calls['c_bid'] == 0).sum(),
    'ask < bid (crossed)':    (calls['c_ask'] < calls['c_bid']).sum(),
    'expiring today (DTE<1)': (calls['dte'] < 1).sum(),
    'duplicate rows':         calls.duplicated(['quote_date', 'expire_date', 'strike']).sum(),
})
problems_table = pd.DataFrame({'rows': problems, '% of all': (100 * problems / len(calls)).round(2)})
problems_table.to_csv(PROCESSED_DIR / 'week1_problem_counts.csv')
problems_table

                          rows  % of all
missing bid or ask       11222      0.07
bid = 0                 857397      5.51
ask < bid (crossed)        186      0.00
expiring today (DTE<1)  301468      1.94
duplicate rows               0      0.00

In [18]:
coverage = calls.groupby('year').agg(
    rows=('mid', 'size'),
    trading_days=('quote_date', 'nunique'),
    first_date=('quote_date', 'min'),
    last_date=('quote_date', 'max'),
)
print(coverage)

calls['moneyness_bucket'] = pd.cut(calls['moneyness'], [0, 0.8, 0.9, 0.97, 1.03, 1.1, 1.2, np.inf],
                                   labels=['<0.80', '0.80-0.90', '0.90-0.97', '0.97-1.03 ATM',
                                           '1.03-1.10', '1.10-1.20', '>1.20'])
calls['dte_bucket'] = pd.cut(calls['dte'], [-1, 7, 30, 90, 180, 365, np.inf],
                             labels=['0-7d', '8-30d', '31-90d', '91-180d', '181-365d', '>1y'])

pd.crosstab(calls['moneyness_bucket'], calls['dte_bucket'], margins=True)

         rows  trading_days first_date  last_date
year
2010   233248           250 2010-01-04 2010-12-31
2011   248382           245 2011-01-03 2011-12-30
2012   324606           250 2012-01-03 2012-12-31
2013   411272           252 2013-01-02 2013-12-31
2014   626775           249 2014-01-03 2014-12-31
2015   984707           252 2015-01-02 2015-12-31
2016   940596           251 2016-01-04 2016-12-30
2017  1023605           250 2017-01-03 2017-12-29
2018  1382559           252 2018-01-02 2018-12-31
2019  1452262           247 2019-01-02 2019-12-31
2020  1736777           250 2020-01-02 2020-12-31
2021  2090995           246 2021-01-04 2021-12-31
2022  2091610           256 2022-01-03 2022-12-30
2023  2009083           249 2023-01-04 2023-12-29

dte_bucket,0-7d,8-30d,31-90d,91-180d,181-365d,>1y,All
moneyness_bucket,,,,,,,
<0.80,36449,87964,96418,101219,147603,158790,628443
0.80-0.90,85936,204439,251968,174535,166838,117868,1001584
0.90-0.97,270280,608237,595620,325814,164514,104605,2069070
0.97-1.03 ATM,355491,890403,674490,316243,129431,81272,2447330
1.03-1.10,347694,815116,668498,322149,133409,83774,2370640
1.10-1.20,286715,642506,679298,349260,162065,101848,2221692
>1.20,365768,932382,1287345,843336,793397,595490,4817718
All,1748333,4181047,4253637,2432556,1697257,1243647,15556477

In [ ]:
years = sorted(calls['year'].unique())
TEST_YEAR  = years[-1]                              
TEST_START = pd.Timestamp(f'{TEST_YEAR}-01-01')
VAL_START  = TEST_START - pd.DateOffset(months=3)   

if len(years) == 1:                                   
    VAL_START  = pd.Timestamp(f'{TEST_YEAR}-09-01')
    TEST_START = pd.Timestamp(f'{TEST_YEAR}-10-01')

calls['split'] = 'train'
calls.loc[calls['quote_date'] >= VAL_START,  'split'] = 'validation'
calls.loc[calls['quote_date'] >= TEST_START, 'split'] = 'test'

split_table = calls.groupby('split')['quote_date'].agg(first='min', last='max', days='nunique', rows='size')
split_table = split_table.reindex(['train', 'validation', 'test'])
split_table

                first       last  days      rows
split
train      2010-01-04 2022-09-30  3186  13022822
validation 2022-10-03 2022-12-30    64    524572
test       2023-01-04 2023-12-29   249   2009083

In [20]:
split_info = {
    'train':      [str(calls['quote_date'].min().date()), str((VAL_START - pd.Timedelta(days=1)).date())],
    'validation': [str(VAL_START.date()), str((TEST_START - pd.Timedelta(days=1)).date())],
    'test':       [str(TEST_START.date()), str(calls['quote_date'].max().date())],
    'target':     'mid = (c_bid + c_ask) / 2',
}
with open(PROCESSED_DIR / 'split.json', 'w') as f:
    json.dump(split_info, f, indent=2)

save = calls.drop(columns=['moneyness_bucket', 'dte_bucket'])
save[save['split'] != 'test'].to_parquet(PROCESSED_DIR / 'calls_trainval.parquet', index=False)
save[save['split'] == 'test'].to_parquet(PROCESSED_DIR / 'calls_test.parquet', index=False)
print('Saved:', [p.name for p in PROCESSED_DIR.iterdir()])

Saved: ['calls_test.parquet', 'calls_trainval.parquet', 'split.json', 'week1_problem_counts.csv']